### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "junior12345@gmail.com",
  "password": "babyjunior1"
}

### Login a user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "junior2345@gmail.com",
  "password": "babyjunior"
}


### Find a particular user with a given ID
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth?email=hello@fmail.com

### Delete a user given id
DELETE http:a//localhost:3000/auth/2

### Update a user
PATCH http://localhost:3000/auth/3
content-type: application/json

{
  "password": "hellno"
}

### Get currently signed in user
GET http://localhost:3000/auth/whoami