
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email":"junior@gmail.com",
  "password":"hellojr145"
}

### finding a particular user with a given ID

GET  http://localhost:3000/auth/3

### 
Get http://localhost:3000/auth/?email=junior@gmail.com

### Dele te user with a given id
DELETE  http://localhost:3000/auth/1