### List all messages
GET http://localhost:3000/messages


### Create a new message
POST http://localhost:3000/messages
content-type: application/json

{
  "content": "asdf"
}


### Get a particular message
GET http://localhost:3000/messages/123123123